import { Course } from "../models/courses.interface";

export const courses: Course[] = [
    {
        id: 0,
        description: 'Aprenda os fundamentos de JavaScript e desenvolva habilidades essenciais para programação web.',
        iconUrl: 'https://images.unsplash.com/photo-1581092334394-70a3f5a3f922?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1581091012184-de1c3a1a4a83?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Este curso cobre variáveis, tipos de dados, estruturas de controle, funções e introdução a objetos com JavaScript.',
        category: 'programação',
        lessonsCount: 20,
    },
    {
        id: 1,
        description: 'Introdução ao HTML5 e CSS3 para criação de páginas web modernas.',
        iconUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1618477461609-9c66b8c416f5?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Aprenda a estruturar páginas com HTML5 e estilizar com CSS3, incluindo layouts responsivos e boas práticas.',
        category: 'web design',
        lessonsCount: 15,
    },
    {
        id: 2,
        description: 'Curso completo de React para criação de interfaces dinâmicas.',
        iconUrl: 'https://images.unsplash.com/photo-1633356122321-0a7b4d7778d3?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1621584163075-b5bde0cf2c69?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Explore os fundamentos do React, incluindo componentes, hooks, roteamento e integração com APIs.',
        category: 'programação',
        lessonsCount: 25,
    },
    {
        id: 3,
        description: 'Fundamentos do Node.js para o desenvolvimento de servidores e APIs RESTful.',
        iconUrl: 'https://images.unsplash.com/photo-1631624218203-6b1cf56b142e?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1661956600454-69a3e380b79a?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Aprenda a construir backends escaláveis usando Node.js, Express e banco de dados MongoDB.',
        category: 'backend',
        lessonsCount: 18,
    },
    {
        id: 4,
        description: 'Design UX/UI para iniciantes: crie experiências incríveis para o usuário.',
        iconUrl: 'https://images.unsplash.com/photo-1601933471622-c2c3e0b1b1a0?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1587614295999-6cb8fcf87f1e?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Conheça os princípios de design centrado no usuário, criação de wireframes e uso do Figma para prototipagem.',
        category: 'design',
        lessonsCount: 12,
    },
    {
        id: 5,
        description: 'Angular do zero ao avançado: crie aplicações web robustas.',
        iconUrl: 'https://images.unsplash.com/photo-1663410217412-4ed2f268ad0e?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1663410551193-35d9e5d145ed?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Aprenda a trabalhar com componentes, serviços, formulários reativos e roteamento no Angular.',
        category: 'programação',
        lessonsCount: 30,
    },
    {
        id: 6,
        description: 'Curso prático de Git e GitHub para controle de versão.',
        iconUrl: 'https://images.unsplash.com/photo-1661956600276-d2efb493fe36?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1623692651790-5b3f8ce53b45?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Domine os comandos essenciais do Git, criação de branches, pull requests e integração com GitHub.',
        category: 'ferramentas',
        lessonsCount: 10,
    },
    {
        id: 7,
        description: 'Introdução ao TypeScript para projetos JavaScript mais seguros.',
        iconUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981e?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1612197523561-cb706d645206?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Entenda os tipos, interfaces, classes e outras funcionalidades do TypeScript aplicadas ao desenvolvimento web.',
        category: 'programação',
        lessonsCount: 16,
    },
    {
        id: 8,
        description: 'Criação de APIs com Python e Flask.',
        iconUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1581090700227-1fd06f9729d4?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Desenvolva APIs RESTful com Python usando o framework Flask, incluindo autenticação e testes.',
        category: 'backend',
        lessonsCount: 14,
    },
    {
        id: 9,
        description: 'Fundamentos de Banco de Dados: SQL e NoSQL.',
        iconUrl: 'https://images.unsplash.com/photo-1581091870622-4c4b0971c52f?auto=format&fit=crop&w=64&q=80',
        courseListIcon: 'https://images.unsplash.com/photo-1663410298347-c9c889fa18fd?auto=format&fit=crop&w=64&q=80',
        longDescription: 'Aprenda a modelar bancos de dados relacionais com SQL e explore bancos NoSQL como MongoDB.',
        category: 'banco de dados',
        lessonsCount: 20,
    }
];
