spring.application.name=biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${JWT_SECRET}
google.client-id=223557033127-vltenqsacdah864g3bd3oh1651vgltc7.apps.googleusercontent.com
