ALTER TABLE usuarios
    ALTER COLUMN password DROP NOT NULL;
ALTER TABLE usuarios
    ADD COLUMN provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL';
ALTER TABLE usuarios
    ALTER COLUMN provider DROP DEFAULT;